[package]
name = "argyle"
version = "0.5.6"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2021"
rust-version = "1.56"
description = "A lightweight, agnostic CLI argument parser."
license = "WTFPL"
repository = "https://github.com/Blobfolio/argyle"
readme = "README.md"
exclude = [
	".github",
	".gitignore",
	".righteous-sandbox.json",
	"doc",
	"examples",
	"justfile",
	"release",
]

[package.metadata.docs.rs]
features = [ "docsrs", "dynamic-help" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin" ]

[package.metadata.bashman]
name = "Argyle"
bash-dir = "./"
man-dir = "./"
credits-dir = "./"

[dev-dependencies]
brunch = "0.2.*"

[[bench]]
name = "fm_keykind"
harness = false

[[bench]]
name = "fm_argue"
harness = false

[features]
default = []

# This is just a workaround for Docs.rs; don't enable this if you're a human!
docsrs = []

# Enables ArgyleError::WantsDynamicHelp variant.
dynamic-help = []

[profile.bench]
lto = false
codegen-units = 1
opt-level = 3
