[package]
name = "argyle"
version = "0.4.1"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2018"
description = "A lightweight, agnostic CLI argument parser."
license = "WTFPL"
repository = "https://github.com/Blobfolio/argyle"
readme = "README.md"
exclude = [
	".gitignore",
	".righteous-sandbox.json",
	".travis.yml",
	"about.toml",
	"doc",
	"examples",
	"justfile",
	"release",
]

[package.metadata.docs.rs]
features = [ "dynamic-help" ]
default-target = "x86_64-unknown-linux-gnu"

[dev-dependencies]
brunch = "0.1.*"

[[bench]]
name = "fm_keykind"
harness = false

[features]
default = []
dynamic-help = [] # Enables ArgyleError::WantsDynamicHelp variant.
